version: "3.9"
services:

  server:
    container_name: Server
    image: node
    build:
      context: .
      dockerfile: cloudcomputing/DockerfileServer
    command: "node index.js"
    working_dir: /app/
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo
  
  nginx:
      build:
        context: .
        dockerfile: DockerfileNginx
      container_name: nginx
      hostname: nginx
      ports:
          - "80:80" 
      depends_on:
          - server
  
  mongo:
    image: mongo
    volumes:
      - ./userdata:/data/db
    ports:
      - "27017:27017"    


volumes:
  userdata:
