version: "3.9"
services:

  server:
    container_name: Server
    image: node
    build:
      context: .
      dockerfile: DockerfileServer
    command: "node index.js"
    working_dir: /app/
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - datenbank
 
  datenbank:
    image: 'mongo'
    ports:
      - "27017:27017"
    volumes:
      - userdata:/data/db

volumes:
  userdata:
